import { VariantFeature } from '../services/VariantService';
import { SimpleFeatureSerialized } from '../services/types';
import { Selection } from 'd3';
export default class IsoformAndVariantTrack {
    private static readonly EXON_HEIGHT;
    private static readonly CDS_HEIGHT;
    private static readonly ISOFORM_HEIGHT;
    private static readonly GENE_LABEL_HEIGHT;
    private static readonly MIN_WIDTH;
    private static readonly ISOFORM_TITLE_HEIGHT;
    private static readonly UTR_HEIGHT;
    private static readonly VARIANT_HEIGHT;
    private static readonly TRANSCRIPT_BACKBONE_HEIGHT;
    private static readonly ARROW_HEIGHT;
    private static readonly ARROW_WIDTH;
    private static readonly SNV_WIDTH;
    private static readonly VARIANT_TRACK_HEIGHT;
    private static readonly LABEL_PADDING;
    private static readonly MAX_ROWS;
    private static readonly MAX_ROWS_WITH_FILTER;
    private trackData;
    private variantData;
    private viewer;
    private width;
    private variantFilter;
    private isoformFilter;
    private initialHighlight?;
    private height;
    private transcriptTypes;
    private variantTypes;
    private binRatio;
    private showVariantLabel;
    constructor({ viewer, height, width, transcriptTypes, variantTypes, showVariantLabel, variantFilter, binRatio, isoformFilter, initialHighlight, trackData, variantData, }: {
        viewer: Selection<SVGGElement, unknown, HTMLElement | null, undefined>;
        height: number;
        width: number;
        transcriptTypes: string[];
        variantTypes: string[];
        showVariantLabel?: boolean;
        variantFilter: string[];
        binRatio: number;
        isoformFilter: string[];
        initialHighlight?: string[];
        trackData?: SimpleFeatureSerialized[];
        variantData?: VariantFeature[];
    });
    DrawTrack(): number;
    filterVariantData(variantData: VariantFeature[], variantFilter: string[]): VariantFeature[];
    setInitialHighlight(selectedAlleles: string[], svgTarget: Selection<SVGGElement, unknown, null, undefined>): void;
}
