import { VariantFeature } from '../services/VariantService';
import { SimpleFeatureSerialized } from '../services/types';
import * as d3 from 'd3';
export default class IsoformEmbeddedVariantTrack {
    private static readonly MAX_ROWS;
    private static readonly EXON_HEIGHT;
    private static readonly CDS_HEIGHT;
    private static readonly ISOFORM_HEIGHT;
    private static readonly GENE_LABEL_HEIGHT;
    private static readonly MIN_WIDTH;
    private static readonly ISOFORM_TITLE_HEIGHT;
    private static readonly UTR_HEIGHT;
    private static readonly VARIANT_HEIGHT;
    private static readonly VARIANT_OFFSET;
    private static readonly TRANSCRIPT_BACKBONE_HEIGHT;
    private static readonly ARROW_HEIGHT;
    private static readonly ARROW_WIDTH;
    private static readonly SNV_HEIGHT;
    private static readonly SNV_WIDTH;
    private trackData;
    private variantData;
    private viewer;
    private width;
    private variantFilter;
    private height;
    private transcriptTypes;
    private variantTypes;
    private showVariantLabel;
    private initialHighlight?;
    constructor({ viewer, height, width, transcriptTypes, variantTypes, showVariantLabel, variantFilter, initialHighlight, trackData, variantData, }: {
        viewer: d3.Selection<SVGGElement, unknown, HTMLElement | null, undefined>;
        height: number;
        width: number;
        transcriptTypes: string[];
        variantTypes: string[];
        showVariantLabel?: boolean;
        variantFilter: string[];
        initialHighlight?: string[];
        variantData?: VariantFeature[];
        trackData?: SimpleFeatureSerialized[];
    });
    DrawTrack(): number;
    private filterVariantData;
}
